# Generated by Django 5.2.1 on 2026-05-05 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0002_publickey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'workflows_workflow',
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_workflows', to='documents.document')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_workflows', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Процесс согласования',
                'verbose_name_plural': 'Процессы согласования',
                'db_table': 'workflows_document_workflow',
                'unique_together': {('document', 'workflow')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='users.role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Шаг маршрута',
                'verbose_name_plural': 'Шаги маршрута',
                'db_table': 'workflows_step',
                'ordering': ['step_order'],
                'unique_together': {('workflow', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='StepAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(blank=True, choices=[('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('revision', 'На доработку')], max_length=20, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_assignments', to=settings.AUTH_USER_MODEL)),
                ('document_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workflows.documentworkflow')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workflows.workflowstep')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'db_table': 'workflows_step_assignment',
            },
        ),
    ]
