# Generated by Django 5.2.1 on 2026-05-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_publickey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Соответствие Пользователь-Роль', 'verbose_name_plural': 'Соответствия Пользователь-Роль'},
        ),
    ]
