# Generated by Django 5.2.1 on 2026-05-05 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_document', 'Создание документа'), ('update_document', 'Обновление документа'), ('submit_for_review', 'Отправка на согласование'), ('approve_step', 'Одобрение шага'), ('reject_step', 'Отклонение шага'), ('return_for_revision', 'Возврат на доработку'), ('sign_document', 'Подписание документа'), ('archive_document', 'Архивация документа'), ('start_workflow', 'Запуск маршрута'), ('add_version', 'Добавление версии'), ('register_key', 'Регистрация публичного ключа')], max_length=100)),
                ('target_type', models.CharField(choices=[('Document', 'Документ'), ('DocumentVersion', 'Версия документа'), ('Workflow', 'Маршрут'), ('DocumentWorkflow', 'Процесс согласования'), ('StepAssignment', 'Назначение'), ('Signature', 'Подпись'), ('PublicKey', 'Публичный ключ')], max_length=50)),
                ('target_id', models.BigIntegerField()),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'db_table': 'audit_log',
                'ordering': ['-done_at'],
            },
        ),
    ]
