# Generated by Django 5.2.1 on 2026-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create_user', 'Создание пользователя'), ('deactivate_user', 'Деактивация пользователя'), ('assign_role', 'Назначение роли'), ('remove_role', 'Снятие роли'), ('create_document', 'Создание документа'), ('update_document', 'Обновление документа'), ('add_version', 'Добавление версии'), ('submit_for_review', 'Отправка на согласование'), ('return_for_revision', 'Возврат на доработку'), ('archive_document', 'Архивация документа'), ('start_workflow', 'Запуск маршрута'), ('approve_step', 'Одобрение шага'), ('reject_step', 'Отклонение шага'), ('sign_document', 'Подписание документа'), ('register_key', 'Регистрация публичного ключа')], max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(choices=[('User', 'Пользователь'), ('Document', 'Документ'), ('DocumentVersion', 'Версия документа'), ('Workflow', 'Маршрут'), ('DocumentWorkflow', 'Процесс согласования'), ('StepAssignment', 'Назначение'), ('Signature', 'Подпись'), ('PublicKey', 'Публичный ключ')], max_length=50),
        ),
    ]
